define({
   type:"Bow", 
   distance:true,
   ammo:"Arrow",
   ammoLeft:50,
   meshFile:"assets/bow_skeleton.png",
   reloadTime:50,
   animation:{
       shootLeftBow:{x:1,y:1105,loop:true,frames:9},
       ShootRightBow:{x:1,y:1235,loop:true,frames:9}
   },
   crosshair:{
    color:"#ff3333",
    radius:5,
    position:{
        x:0,
        y:0,
    }
   }
});