define({
   type:"SpearAmmo", 
   distance:0,
   meshFile:"assets/bow.png",
   damage:1,
   drawable:false,
   velocity:{
    x:1.1,
    y:0
   },
   animation:{
       shootLeft:{x:1,y:1105,loop:true,frames:9},
       ShootRightBow:{x:1,y:1235,loop:true,frames:9}
   }
});