define({
   type:"Arrow", 
   distance:10,
   meshFile:"assets/bow.png",
   damage:10,
   velocity:{
    x:32,
    y:0
   },
   animation:{
       shootLeft:{x:1,y:1105,loop:true,frames:9},
       ShootRight:{x:1,y:1235,loop:true,frames:9}
   }
});