define({
   type:"Arrow", 
   distance:500,
   meshFile:"assets/bow.png",
   damage:10,
   drawable:true,
   velocity:{
    x:80,
    y:0
   },
   animation:{
       shootLeft:{x:1,y:1105,loop:true,frames:9},
       ShootRightBow:{x:1,y:1235,loop:true,frames:9}
   }
});