define({
   type:"Arrow", 
   distance:300,
   meshFile:"assets/bow.png",
   damage:10,
   velocity:{
       x:30,y:0
   },
   animation:{
       shootLeft:{x:1,y:1105,loop:true,frames:9},
       ShootRight:{x:1,y:1235,loop:true,frames:9}
   }
});